### PR TITLE
Add an option to define custom list key as idParam

### PR DESCRIPTION
**Pull request by jabzzy**
Greetings. 

Thought you might find this useful to be in the upstream repo. Quickly reviewed couple of other forks and there were not too many nice solutions, imo. And for some reason, they aren't ported here :) 

Any thoughts on this one?

### CODE REVIEW

**Comment by mfitzhenry** [comment]
@jabzzy - Thanks!  Would love to know what in your Keystone config required this change?

**Comment by jabzzy** [comment]
@mfitzhenry, I've set up static pages model and a controller for them with matching route, that looks like this — `/:page`. I need to be able to change page slugs, hence I didn't use the autokey feature.

If I'm doing it wrong, would love to hear about a more appropriate solution :)

I'm using latest beta of KS.

**Comment by mfitzhenry** [comment]
@s-plum thoughts?

**Comment by jabzzy** [comment]
sooo, any update on this? :)

**Pull request closed without merging**
